language: cpp
compiler:
  - gcc
  - clang

os:
  - linux
  - osx

dist: trusty
sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      - gcc-5
      - g++-5
      - clang-3.7

env:
  matrix:
    - BUILDTYPE=Release
    - BUILDTYPE=Debug

matrix:
  include:
    - os: linux
      compiler: gcc
      env: COMPILER=g++-5
    - os: linux
      compiler: clang
      env: COMPILER=clang++-3.7
    - os: osx
      compiler: clang
  exclude:
    - os: osx
      compiler: gcc

script:
  - mkdir -p ../build
  - cd ../build
  - cmake -DCMAKE_BUILD_TYPE=${BUILDTYPE} ../state_ptr
  - cmake --build . --config Release
  - ctest -V -C Release
