language: cpp
compiler:
  - gcc
  - clang

os:
  - linux

dist: trusty
sudo: required

env:
  matrix:
    - BUILDTYPE=Release
    - BUILDTYPE=Debug

matrix:
    # from https://docs.travis-ci.com/user/languages/cpp/
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env:
        - MATRIX_EVAL="CC=clang-3.7 && CXX=clang++-3.7"

script:
  - eval "${MATRIX_EVAL}"
  - if []
  - mkdir -p ../build
  - cd ../build
  - cmake -DCMAKE_BUILD_TYPE=${BUILDTYPE} ../state_ptr
  - cmake --build . --config Release
  - ctest -V -C Release
