language: cpp
compiler:
  - gcc
  - clang

os:
  - linux

dist: trusty
sudo: required

env:
  matrix:
    - BUILDTYPE=Release
    - BUILDTYPE=Debug

  addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.7
      packages:
        - g++-6
        - clang-3.7

matrix:
    - os: linux
      compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang-3.7 && CXX=clang++-3.7"

script:
  - eval "${MATRIX_EVAL}"
  - if []
  - mkdir -p ../build
  - cd ../build
  - cmake -DCMAKE_BUILD_TYPE=${BUILDTYPE} ../state_ptr
  - cmake --build . --config Release
  - ctest -V -C Release
