language: cpp
compiler:
  - gcc
  - clang

os:
  - linux

dist: trusty
sudo: required

env:
  matrix:
    - BUILDTYPE=Release
    - BUILDTYPE=Debug

before_script:
  - if [ `uname` = "Linux" ]; then
      sudo add-apt-repository -y ubuntu-toolchain-r-test ;
      sudo add-apt-repository -y llvm-toolchain-precise-3.7 ;
      sudo apt-get update ;
  - if [ "${COMPILER}" = "gcc" ]; then
      sudo apt-get install -y --force-yes g++-6 ;
      export CC=gcc-6 ;
      export CXX=g++-6 ;
    fi
  - if [ "${COMPILER}" = "clang" ]; then
      sudo apt-get install -y --force-yes clang-3.7 ;
      export CC=clang-3.7 ;
      export CXX=clang++-3.7 ;
    fi

script:
  - mkdir -p ../build
  - cd ../build
  - cmake -DCMAKE_BUILD_TYPE=${BUILDTYPE} ../state_ptr
  - cmake --build . --config Release
  - ctest -V -C Release
